---
ip_community_lists:
  - name:  NCFDMZ_DA2_PREF_COMM
    entries:
      - action: permit
        communities: [64811:11024]
  - name:  NCFDMZ_DC21_PREF_COMM
    entries:
      - action: permit
        communities: [64813:11025]
custom_structured_configuration_route_maps:
  - name: DENY_ALL
    sequence_numbers: 
      - sequence: 10
        type: deny  
  - name: NCFDMZ_PREF_DEFAULT_IMPORT_MAP
    sequence_numbers: 
      - sequence: 10
        type: permit
        description: "PRIMARY DA2 DEFAULT (LP 170)"
        match:
          - "community NCFDMZ_DA2_PREF_COMM"
        set:
          - "local-preference 170"
      - sequence: 20
        type: permit
        description: "SECONDARY DC21 DEFAULT (LP 150)"  
        match:
          - "community NCFDMZ_DC21_PREF_COMM"
        set:
          - "local-preference 150"         
      - sequence: 900
        type: permit
        description: "Standard import map to allow All routes"
  - name: PASS_ALL
    sequence_numbers: 
      - sequence: 10
        type: permit
  - name: PREF_DEFAULT_IMPORT_MAP
    sequence_numbers: 
      - sequence: 10
        type: permit
        description: "Standard import map to allow DA2 Default"
        match:
          - "community DA2_DEFAULT_COMM"
        set:
          - "local-preference 150"
      - sequence: 20
        type: permit
        description: "Standard import map to allow DC21 Default"
        match:
          - "community DC21_DEFAULT_COMM"
        set:
          - "local-preference 120"
      - sequence: 900
        type: permit
        description: "description Standard import map to allow All routes"
  - name: RM_FILTERED_1NET_BGP_POLICY_OUT
    sequence_numbers: 
      - sequence: 10
        type: permit
        match:
          - "ip address prefix-list PL_RFC1918"
      - sequence: 20
        type: permit
        match:
          - "ip address prefix-list PL_DEFAULT"    
  - name: RM_FILTERED_TRUST_OUT
    sequence_numbers: 
      - sequence: 10
        type: permit
        match:
          - "ip address prefix-list PL_DEFAULT"
      - sequence: 20
        type: permit
        match:
          - "ip address prefix-list PL_RFC1918"          
  - name: STANDARD_1NET_BGP_POLICY_IN
    sequence_numbers: 
      - sequence: 10
        type: permit
        match:
          - "community POLICY_LP20_BLEED"
        set:
          - "local-preference 20"
      - sequence: 20
        type: permit
        match:
          - "community POLICY_LP190_OVERRIDE"
        set:
          - "local-preference 190"
      - sequence: 30
        type: permit
        match:
          - "community POLICY_LP120"
        set:
          - "local-preference 120"
      - sequence: 40
        type: permit
        match:
          - "community POLICY_LP150"
        set:
          - "local-preference 150"
      - sequence: 50
        type: permit
        match:
          - "community POLICY_LP170"
        set:
          - "local-preference 170"
      - sequence: 60
        type: permit
        match:
          - "community POLICY_LP180"
        set:
          - "local-preference 180" 
      - sequence: 500
        type: permit
        description: "PERMIT_ALL_ROUTES"
  - name: STANDARD_1NET_BGP_POLICY_OUT
    sequence_numbers: 
      - sequence: 10
        type: permit       
  - name: TEST_DC_RM
    sequence_numbers:
    - sequence: 10
      type: permit
      description: "THIS IS A TEST AVD ROUTE MAP FOR DC"
      match:
        - "community TEST_COMM_DC"
      set:
        - "local-preference 150"

ip_access_lists:
  - name: ACL_RO_TRAFFIC_INBOUND
    entries:
      - sequence: 10
        action: permit
        protocol: ip
        source: 10.0.0.0/8
        destination: any
      - sequence: 20
        action: deny
        protocol: ip
        source: any
        destination: any
