---



tenants:
  - name: OB1
    # enable_mlag_ibgp_peering_vrfs: True
    vrfs:
      - name: default
        # bgp_peers:
        #   #OB1 to both PEs
        #   - ip_address: "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe1_ip }}"
        #     peer_group: "PE_CE_OB1"
        #     description: MCO-TRX1-CONCENTRIX-PE1
        #     nodes:
        #       - mco-ob1-concentrix-n1
        #   - ip_address: "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe2_ip }}"
        #     peer_group: "PE_CE_OB1"
        #     description: MCO-TRX1-CONCENTRIX-PE2
        #     nodes:
        #       - mco-ob1-concentrix-n1
        svis:
        - id: 1001
          name: OB1:MGMT
          enabled: true
          nodes:
            - node: "{{ groups['3PCC_OB'][0] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][0]].vlan_1001_ip + '/28'  }}"
            - node: "{{ groups['3PCC_OB'][1] }}"
              ip_address:  "{{ hostvars[groups['3PCC_OB'][1]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][2] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][2]].vlan_1001_ip + '/24'  }}"
          # profile: MGMT-1
          # tags:
          #   - SP

        # l3_interfaces:
        # - interfaces: [ Port-Channel11 , Port-Channel12 ]
        #   nodes: [ "{{ groups['3PCC_OB'][0] }}", "{{ groups['3PCC_OB'][0] }}" ]
        #   description: L3-PtP:OVERLAY:OB1:PE-CE
        #   enabled: true
        #   ip_addresses:
        #     - "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe1_local_ip + '/31' }}"
        #     - "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe2_local_ip + '/31' }}"
        #   structured_config:
        #     bfd:
        #       interval: 150
        #       min_rx: 150
        #       multiplier: 150



