---

fabric_name: OB_FABRIC

transceiver_qsfp_default_mode_4x10: false
bgp_peer_groups:
  ipv4_underlay_peers:
    name: PE_CE_OB1
    bfd: true
    password: LrxdPchq0LiOI2Jz39Pe5Q==
    structured_config:
      remote_as: 64800
      route_map_in: DEFAULT_ROUTE
      route_map_out: OB1_3PCC_POLICY_OUT

bgp_ecmp: 2
bgp_maximum_paths: 2


# TODO: Validate if default config should be generated. None of these configs render at all with this turned off.
generate_default_config: True

# Perform config backup before config replace
eos_config_deploy_eapi_pre_running_config_backup: true

pre_running_config_backup_filename: "{{ inventory_hostname }}_pre_running-config.conf"
pre_running_config_backup_dir_name: 'config_backup'
pre_running_config_backup_dir: '{{ inventory_dir }}/{{ pre_running_config_backup_dir_name }}'

# TODO: This can be inherited from global vars > need to check why is this section commented out in global_vars wan_common_management.yml
management_ssh:
  access_groups:
    - name: SSH_ACCESS
      vrf: "{{ mgmt_interface_vrf }}"
  idle_timeout: 10
  vrfs:
    - name: "{{ mgmt_interface_vrf }}"
      enable: true

node_type_keys:
  - key: l3router
    type: l3router
    connected_endpoints: true
    default_evpn_role: none
    default_overlay_routing_protocol: none
    mlag_support: true
    network_services:
      l2: true
      l3: true
    underlay_router: true
    uplink_type: p2p
    ip_addressing:
      router_id: router_id.j2
