---
mgmt_interface: Vlan1001
mgmt_interface_vrf: default
management_gateway: 10.192.17.1

l3router:
  defaults:
    loopback_ipv4_pool: 10.9.176.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_mode: mstp
    bgp_as: 64801
    bgp_defaults:
      - update wait-install
      - no bgp default ipv4-unicast
      - distance bgp 20 200 200
      - graceful-restart restart-time 300
      - graceful-restart
    bfd_multihop:
      interval: 300
      min_rx: 300
      multiplier: 3
    raw_eos_cli: |
      dhcp relay
        vss control disabled
      !
      ip dhcp relay information option
      ip dhcp relay always-on
      ip dhcp relay all-subnets default
      !
      management ssh
        authentication mode password
      !
      arp aging timeout default 900
      !
      system control-plane
        no service-policy input copp-system-policy
      !
      spanning-tree mst configuration
        name OB1
    structured_config:
      # spanning_tree:
      #   mst_instances:
      #   - id: 0
      #     priority: 4096
      vlan_interfaces:
        - name: Vlan1001
          description: OB1:MGMT
          ip_helpers:
            - ip_helper: 10.132.30.7
            - ip_helper: 10.229.88.5
      router_bfd:
        multihop:
          interval: 300
          min_rx: 300
          multiplier: 3
      route_maps:
        - name: OB1_3PCC_POLICY_OUT
          sequence_numbers:
            - sequence: 10
              type: permit
              description: OB1_3PCC_POLICY_OUT
              match:
                - ip address prefix-list OB1_3PCC_POLICY_OUT
        - name: DEFAULT_ROUTE
          sequence_numbers:
            - sequence: 10
              type: permit
              match:
                - ip address prefix-list DEFAULT_ROUTE

  node_groups:
    - group: mco-ob1-concentrix-n1
      # uplink_switches: ['mco-trx1-concentrix-pe1', 'mco-trx1-concentrix-pe2']
      # uplink_interfaces: ['Ethernet13', 'Ethernet14']
      platform: 710P
      nodes:
        - name: mco-ob1-concentrix-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action:  "{{ 'permit' + hostvars[groups['3PCC_OB'][0]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action:  "{{ 'permit' + hostvars[groups['3PCC_OB'][0]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][0]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][0]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][0]].ob1_pe2_local_ip + '/31' }}"
          # l3_port_channels: #supported in 5.2 , not in 4.10
    - group: den-ob1-qualfon-n1
      nodes:
        - name: den-ob1-qualfon-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + ' ' + hostvars[groups['3PCC_OB'][1]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + ' ' + hostvars[groups['3PCC_OB'][1]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][1]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][1]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][1]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][1]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][1]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][1]].ob1_pe2_local_ip + '/31' }}"
    - group: den-ob1-ttech-n1
      nodes:
        - name: den-ob1-ttech-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][2]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][2]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][2]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][2]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][2]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][2]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][2]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][2]].ob1_pe2_local_ip + '/31' }}"
    - group: dfw-ob1-foundever-n1
      nodes:
        - name: dfw-ob1-foundever-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][3]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][3]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][3]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][3]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][3]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][3]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][3]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][3]].ob1_pe2_local_ip + '/31' }}"
    - group: dfw-ob1-telepf-n1
      nodes:
        - name: dfw-ob1-telepf-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][4]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][4]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][4]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][4]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][4]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][4]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][4]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][4]].ob1_pe2_local_ip + '/31' }}"
    - group: dtw-ob1-qualfon-n1
      nodes:
        - name: dtw-ob1-qualfon-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][5]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][5]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][5]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][5]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][5]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][5]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][5]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][5]].ob1_pe2_local_ip + '/31' }}"
    - group: iad-ob1-ttech-n1
      nodes:
        - name: iad-ob1-ttech-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][6]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][6]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][6]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][6]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][6]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][6]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][6]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][6]].ob1_pe2_local_ip + '/31' }}"
    - group: oma-ob1-foundever-n1
      nodes:
        - name: oma-ob1-foundever-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][7]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][7]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][7]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][7]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][7]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][7]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][7]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][7]].ob1_pe2_local_ip + '/31' }}"
    - group: slc-ob1-telepf-n1
      nodes:
        - name: slc-ob1-telepf-n1
          id: 1
          structured_config:
            prefix-list:
              - name: OB1_3PCC_POLICY_OUT
                sequence_numbers:
                  - sequence: 5
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][8]].policy_out_ip + '/28' }}"
                  - sequence: 10
                    action: "{{ 'permit' + hostvars[groups['3PCC_OB'][8]].Loopback0 + '/32'}}"
            router_bgp:
              neighbors:
                - ip_address: "{{ hostvars[groups['3PCC_OB'][8]].ob1_pe1_ip }}"
                  peer_group: "PE_CE_OB1"
                - ip_address: "{{ hostvars[groups['3PCC_OB'][8]].ob1_pe2_ip }}"
                  peer_group: "PE_CE_OB1"
              address_family_ipv4:
                networks:
                  - prefix: "{{ hostvars[groups['3PCC_OB'][8]].Loopback0 + '/32'}}"
                  - prefix: "{{ hostvars[groups['3PCC_OB'][8]].policy_out_ip + '/28' }}"
          l3_interfaces:
            - profile: PE
              name: Port-Channel11
              ip_address: "{{ hostvars[groups['3PCC_OB'][8]].ob1_pe1_local_ip + '/31' }}"
            - profile: PE
              name: Port-Channel12
              ip_address: "{{ hostvars[groups['3PCC_OB'][8]].ob1_pe2_local_ip + '/31' }}"
              # description: L3-PtP:OVERLAY:OB1:PE-CE
              # raw_eos_cli: bfd interval 150 min-rx 150 multiplier 150

tenants:
  - name: OB1
    vrfs:
      - name: default
        svis:
        - id: 1001
          name: OB1:MGMT
          enabled: true
          nodes:
            - node: "{{ groups['3PCC_OB'][0] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][0]].vlan_1001_ip + '/28'  }}"
            - node: "{{ groups['3PCC_OB'][1] }}"
              ip_address:  "{{ hostvars[groups['3PCC_OB'][1]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][2] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][2]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][3] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][3]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][4] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][4]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][5] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][5]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][6] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][6]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][7] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][7]].vlan_1001_ip + '/24'  }}"
            - node: "{{ groups['3PCC_OB'][8] }}"
              ip_address: "{{ hostvars[groups['3PCC_OB'][8]].vlan_1001_ip + '/24'  }}"