# ---
# custom_host_configuration_route_maps:
#   - name: DENY_ALL
#     sequence_numbers:
#     - sequence: 10
#       type: deny
#   - name: PASS_ALL
#     sequence_numbers:
#     - sequence: 10
#       type: permit
#   - name: PASS_DEFAULT_ONLY
#     sequence_numbers:
#     - sequence: 10
#       type: permit
#       match:
#         - "ip address prefix-list PL_DEFAULT"

