ROUTER_BGP_ADR_FAMILY: |-
  address-family ipv4
    neighbor PE_CE_OB1 activate
    neighbor PE_CE_3PCC activate
    !
    address-family vpn-ipv4
    neighbor RR_PEERS activate
    no neighbor default encapsulation mpls next-hop-self source-interface Loopback0

ROUTER_BGP_OB1_VRF: |-
  vrf OB1
    rd {{Loopback0}}:900
    route-target import vpn-ipv4 64800:900
    route-target import vpn-ipv4 64801:900101
    route-target export vpn-ipv4 64800:900
    router-id {{Loopback0}}
    maximum-paths 2 ecmp 2
    neighbor {{vrf_ob1.pe_ce_n1}} peer group PE_CE_OB1
    neighbor {{vrf_ob1.pe_ce_n1}} description OB1-N1:OB1

ROUTER_BGP_3PCC_PG: |-
  neighbor PE_CE_3PCC peer group
    neighbor PE_CE_3PCC local-as 7838 no-prepend replace-as
    neighbor PE_CE_3PCC timers 2 5
    neighbor PE_CE_3PCC bfd
    neighbor PE_CE_3PCC send-community
    neighbor PE_CE_3PCC remove-private-as
    neighbor PE_CE_3PCC route-map 3PCC_VENDOR_PRIORITY-1_IN in
    neighbor PE_CE_3PCC route-map 3PCC_VENDOR_PRIORITY-1_OUT out

ROUTER_BGP_VNX1_VRF: |-
  vrf VNX1
    rd {{Loopback0}}:920
    route-target import vpn-ipv4 65420:90311
    route-target import vpn-ipv4 65526:90312
    route-target import vpn-ipv4 65500:903
    route-target import vpn-ipv4 64840:90301
    route-target import vpn-ipv4 64840:90302
    route-target import vpn-ipv4 64840:90303
    route-target import vpn-ipv4 64800:903
    route-target export vpn-ipv4 64800:903
    router-id {{Loopback0}}
    maximum-paths 2 ecmp 2
    neighbor {{vrf_vnx1.pe_ce_n1}} remote-as {{VENDOR_ASN}}
    neighbor {{vrf_vnx1.pe_ce_n1}} peer group PE_CE_3PCC
    neighbor {{vrf_vnx1.pe_ce_n1}} description {{VENDOR_NAME}}:VENDOR_DEVICE
    neighbor {{vrf_vnx1.pe_ce_n1}} password 7 $1c$O/K5nO7RsL6PAxl7mDsL0Q==
