INTERFACE_CONFIG: |-
    interface Port-Channel1
      description P-P:ATL-TRX1-DC1-P2:Po1
      no switchport
      ip address 10.199.1.76/31
      mpls ldp interface
      ip ospf network point-to-point
      ip ospf authentication message-digest
      ip ospf area 0.0.0.0
      ip ospf message-digest-key 1 md5 7 S855yxQDW7ozhPiz4EoSqQ==
    !
    interface Ethernet1/1
      description P-P:DFW-TRX1-DALEQ-P1:Hu0/0/0/11:Verizon:CID#W1E67717
      no shutdown
      mtu 9184
      no switchport
      ip address 10.199.1.68/31
      mpls ldp interface
      mac security profile MKA_AES_256
      ip ospf network point-to-point
      ip ospf authentication message-digest
      ip ospf area 0.0.0.0
      ip ospf message-digest-key 1 md5 7 yc2q2lnRSpoNVOBBVUvITA==
    !

    interface Ethernet2/1
      description P-P:IAD-TRX1-DC21-P2:Eth4/1:ATT:CID#L8YX881949ATI
      no shutdown
      mtu 9184
      no switchport
      ip address 10.199.1.70/31
      mpls ldp interface
      mac security profile MKA_AES_256
      ip ospf network point-to-point
      ip ospf authentication message-digest
      ip ospf area 0.0.0.0
      ip ospf message-digest-key 1 md5 7 gymNWewoZb5r3GPCx5ez3Q==
    !

    interface Ethernet25/1
      description P-PE:ATL-TRX1-DC1-PE1:E25/1
      no shutdown
      no switchport
      ip address 10.199.2.42/31
      mpls ldp interface
      mac security profile MKA_AES_256
      ip ospf network point-to-point
      ip ospf authentication message-digest
      ip ospf area 0.0.0.0
      ip ospf message-digest-key 1 md5 7 gI+W5b1R4lDpehCmYzyW2w==
    !

    interface Ethernet26/1
      description P-PE:ATL-TRX1-DC1-PE2:E25/1
      no shutdown
      no switchport
      ip address 10.199.2.46/31
      mpls ldp interface
      mac security profile MKA_AES_256
      ip ospf network point-to-point
      ip ospf authentication message-digest
      ip ospf area 0.0.0.0
      ip ospf message-digest-key 1 md5 7 2N0AcrEZMpyItTIpN+dU7Q==
    !

    interface Ethernet31/1
      no shutdown
      no switchport
      channel-group 1 mode active
      mac security profile MKA_AES_256
    !
    interface Ethernet32/1
      no shutdown
      no switchport
      channel-group 1 mode active
      mac security profile MKA_AES_256
    !
    interface Ethernet32/3
      shutdown
      no switchport
    !

    interface Loopback0
      description MPLS_Overlay_peering
      ip address 10.199.0.40/32
      ip ospf area 0.0.0.0
    !
    interface Management1
      description oob_management
      no shutdown
      vrf MGMT
      ip address 10.9.182.150/28
    !

# port_profiles:
#   - profile: not_used
#     enabled: false
#     raw_eos_cli: |-
#       no switchport
network_ports:
  - switches:
      - atl-trx1-dc1-p1
    # profile: not_used
    switch_ports:
    - Ethernet1/1-4
    - Ethernet2/1-4
    - Ethernet3/1-4
    - Ethernet4/1-4
    - Ethernet5/1-4
    - Ethernet6/1-4
    - Ethernet7/1-4
    - Ethernet8/1-4
    - Ethernet9/1-4
    - Ethernet10/1-4
    - Ethernet11/1-4
    - Ethernet12/1-4
    - Ethernet13/1-4
    - Ethernet14/1-4
    - Ethernet15/1-4
    - Ethernet16/1-4
    - Ethernet17/1-4
    - Ethernet18/1-4
    - Ethernet19/1-4
    - Ethernet20/1-4
    - Ethernet21/1-4
    - Ethernet22/1-4
    - Ethernet23/1-4
    - Ethernet24/1-4
    - Ethernet25/2-4
    - Ethernet26/2-4
    - Ethernet27/1-4
    - Ethernet28/1-4
    - Ethernet29/1-4
    - Ethernet30/1-3
    - Ethernet31/2-4
    - Ethernet33/1-8
    - Ethernet34/1-8
    - Ethernet35/1-8
    - Ethernet36/1-8
    # enabled: false 
    raw_eos_cli:
      no switchport
      shutdown