---

fabric_name: OB_FABRIC




bgp_peer_groups:
  ipv4_underlay_peers:
    name: PE_CE_OB1

# loopback_ipv4_pool: 10.48.26.0/24



# TODO: Validate if default config should be generated. None of these configs render at all with this turned off.
generate_default_config: True

# Perform config backup before config replace
eos_config_deploy_eapi_pre_running_config_backup: true

pre_running_config_backup_filename: "{{ inventory_hostname }}_pre_running-config.conf"
pre_running_config_backup_dir_name: 'config_backup'
pre_running_config_backup_dir: '{{ inventory_dir }}/{{ pre_running_config_backup_dir_name }}'


node_type_keys:
  - key: l3router
    type: l3router
    connected_endpoints: true
    default_evpn_role: none
    default_overlay_routing_protocol: none
    mlag_support: true
    network_services:
      l2: true
      l3: true
    underlay_router: true
    uplink_type: p2p