port_profiles:
  - profile: PE
    structured_config:
      spanning_tree_bpduguard: True
      spanning_tree_portfast: edge
    # mode: routed


interface_profiles:
  - name: MGMT
    commands:
      - description mgmt interface
      - switchport access vlan 110
      - spanning-tree portfast
      - no spanning-tree portfast auto
      - spanning-tree bpduguard enable

network_ports:
  - switches:
      - mco-ob1-concentrix-n1
    switch_ports:
      - Ethernet1-12
    structured_config:
      profile: MGMT

routers:
  - name: MCO-TRX1-CONCENTRIX-PE1
    adapters:
      - endpoint_ports: ['Ethernet4/1']
        switch_ports: ['Ethernet13']
        switches: [mco-ob1-concentrix-n1]
        profile: PE
        port_channel:
          mode: active
          channel_id: 11
  - name: MCO-TRX1-CONCENTRIX-PE2
    adapters:
      - endpoint_ports: ['Ethernet4/1']
        switch_ports: ['Ethernet14']
        switches: [mco-ob1-concentrix-n1]
        profile: PE
        port_channel:
          mode: active
          channel_id: 12


# core_interfaces:
#   p2p_links_profiles:
#     - name: pe_ce_p2p_profile
#       mtu: 1500
#       mpls_ip: false
#       include_in_underlay_protocol: false
#   p2p_links:
#     - nodes: [ MCO-TRX1-CONCENTRIX-PE1 , mco-ob1-concentrix-n1 ]
#       id: 1
#       port_channel:
#         mode: active
#         nodes_child_interfaces:
#           - node: MCO-TRX1-CONCENTRIX-PE1
#             interfaces: [ Ethernet4 ]
#             channel_id: 11
#           - node: mco-ob1-concentrix-n1
#             interfaces: [ Ethernet13 ]
#             channel_id: 11