---
- name: Build Switch configuration
  hosts: "{{ target_hosts }}"
  gather_facts: false
  vars:
    ansible_user: nsauto
  vars_files:
    - ../local_vault.yml
  collections:
    - arista.avd

# ANTA requirements
# anta==0.14.0
# pyrsistent

  tasks:
    - name: Generate State Validation
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        save_catalog: true