---
eos_cli: |-
  !
  {{MAC_SEC}}
  !
  {{VRF_DEFINITION}}
  !
  {{INTERFACE_CONFIG}}
  !
  {{MPLS_DEFAULTS}}
  !
  {{ROUTER_BGP_DEFAULTS}}

    {{ROUTER_BGP_PE_CE_DC_OB_SOB_DCX1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PCI_SE_CCHYBRID_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PCI_SE_CCISSUE_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PCI_SE_CCMERCH_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PCI_SE_DCX1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PCI_SE_PEN1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PROD_SI_BUSINTEL_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PROD_SI_DCX1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PROD_SI_DMZMEM1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PROD_SI_NFCDMZ_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_PROD_SI_USX1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_TEST_ST_DCX1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_TEST_ST_IDTN_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_TEST_ST_IDTNB2B_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_TEST_ST_IDTNNDX_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_USUNT1_PG}}
    !
    {{ROUTER_BGP_PE_CE_DC_USX1_PG}}
    !
    {{ROUTER_RR_PEERS_PG}}
    !!
    {{ROUTER_BGP_ADR_FAMILY}}
    !
    {{ROUTER_BGP_BUSINTEL_VRF}}
    !
    {{ROUTER_BGP_CCHYBRID_VRF}}
    !
    {{ROUTER_BGP_CCISSUE_VRF}}
    !
    {{ROUTER_BGP_CCMERCH_VRF}}
    !
    {{ROUTER_BGP_DCX1_VRF}}
    !
    {{ROUTER_BGP_DMZMEM1_VRF}}
    !
    {{ROUTER_BGP_IDTN_VRF}}
    !
    {{ROUTER_BGP_IDTNB2B_VRF}}
    !
    {{ROUTER_BGP_IDTNDX_VRF}}
    !
    {{ROUTER_BGP_NCFDMZ_VRF}}
    !
    {{ROUTER_BGP_OB1_VRF}}
    !
    {{ROUTER_BGP_PEN1_VRF}}
    !
    {{ROUTER_BGP_UNUNT1_VRF}}
    !
    {{ROUTER_BGP_USX1_VRF}}
    !
  !
  {{MGMT_DEFAULTS}}
