INTERFACE_CONFIG: |-
  !
  interface Port-Channel110
    description PE-CE:ATL-SI1-DC1-N1:Po101
    no switchport
  !
  interface Port-Channel110.2001
    description PE-CE:ATL-SI1-DC1-N1:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.64.0.0/31
  !
  interface Port-Channel110.2002
    description PE-CE:ATL-SI1-DC1-N1:Po101.2002
    encapsulation dot1q vlan 2002
    vrf DMZMEM1
    ip address 10.64.0.2/31
  !
  interface Port-Channel110.2004
    description PE-CE:ATL-SI1-DC1-N1:Po101.2004
    encapsulation dot1q vlan 2004
    vrf BUSINTEL
    ip address 10.64.0.4/31
  !
  interface Port-Channel110.2006
    description PE-CE:ATL-SI1-DC1-N1:Po101.2006
    encapsulation dot1q vlan 2006
    vrf NCFDMZ
    ip address 10.64.0.6/31
  !
  interface Port-Channel110.2008
    description PE-CE:ATL-SI1-DC1-N1:Po101.2008
    encapsulation dot1q vlan 2008
    vrf USX1
    ip address 10.64.0.8/31
  !
  interface Port-Channel111
    description PE-CE:ATL-SI1-DC1-N2:Po101
    no switchport
  !
  interface Port-Channel111.2001
    description PE-CE:ATL-SI1-DC1-N2:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.64.0.20/31
  !
  interface Port-Channel111.2002
    description PE-CE:ATL-SI1-DC1-N2:Po101.2002
    encapsulation dot1q vlan 2002
    vrf DMZMEM1
    ip address 10.64.0.22/31
  !
  interface Port-Channel111.2004
    description PE-CE:ATL-SI1-DC1-N2:Po101.2004
    encapsulation dot1q vlan 2004
    vrf BUSINTEL
    ip address 10.64.0.24/31
  !
  interface Port-Channel111.2006
    description PE-CE:ATL-SI1-DC1-N2:Po101.2006
    encapsulation dot1q vlan 2006
    vrf NCFDMZ
    ip address 10.64.0.26/31
  !
  interface Port-Channel111.2008
    description PE-CE:ATL-SI1-DC1-N2:Po101.2008
    encapsulation dot1q vlan 2008
    vrf USX1
    ip address 10.64.0.28/31
  !
  interface Port-Channel114
    description PE-CE:ATL-ST1-DC1-N1:Po101
    no switchport
  !
  interface Port-Channel114.2001
    description PE-CE:ATL-ST1-DC1-N1:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.72.0.0/31
  !
  interface Port-Channel114.3001
    description PE-CE:ATL-ST1-DC1-N1:Po101.3001
    encapsulation dot1q vlan 3001
    vrf IDTN
    ip address 10.72.0.2/31
  !
  interface Port-Channel114.3002
    description PE-CE:ATL-ST1-DC1-N1:Po101.3002
    encapsulation dot1q vlan 3002
    vrf IDTNDX
    ip address 10.72.0.4/31
  !
  interface Port-Channel114.3003
    description PE-CE:ATL-ST1-DC1-N1:Po101.3003
    encapsulation dot1q vlan 3003
    vrf IDTNB2B
    ip address 10.72.0.6/31
  !
  interface Port-Channel115
    description PE-CE:ATL-ST1-DC1-N2:Po101
    no switchport
  !
  interface Port-Channel115.2001
    description PE-CE:ATL-ST1-DC1-N2:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.72.0.16/31
  !
  interface Port-Channel115.3001
    description PE-CE:ATL-ST1-DC1-N2:Po101.3001
    encapsulation dot1q vlan 3001
    vrf IDTN
    ip address 10.72.0.18/31
  !
  interface Port-Channel115.3002
    description PE-CE:ATL-ST1-DC1-N2:Po101.3002
    encapsulation dot1q vlan 3002
    vrf IDTNDX
    ip address 10.72.0.20/31
  !
  interface Port-Channel115.3003
    description PE-CE:ATL-ST1-DC1-N2:Po101.3003
    encapsulation dot1q vlan 3003
    vrf IDTNB2B
    ip address 10.72.0.22/31
  !
  interface Port-Channel116
    description PE-CE:ATL-SOB1-DC1-N1:Po101
    no switchport
  !
  interface Port-Channel116.2001
    description PE-CE:ATL-SOB1-DC1-N1:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.76.0.130/31
  !
  interface Port-Channel117
    description PE-CE:ATL-SOB1-DC1-N2:Po101
    no switchport
  !
  interface Port-Channel117.2001
    description PE-CE:ATL-SOB1-DC1-N2:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.76.0.138/31
  !
  interface Port-Channel211
    description PE-CE:ATL-SE1-DC1-N1:Po101
    no switchport
  !
  interface Port-Channel211.2001
    description PE-CE:ATL-SE1-DC1-N1:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.77.0.0/31
  !
  interface Port-Channel211.2002
    description PE-CE:ATL-SE1-DC1-N1:Po101.2002
    encapsulation dot1q vlan 2002
    vrf PEN1
    ip address 10.77.0.2/31
  !
  interface Port-Channel211.2004
    description PE-CE:ATL-SE1-DC1-N1:Po101.2004
    encapsulation dot1q vlan 2004
    vrf CCISSUE
    ip address 10.77.0.4/31
  !
  interface Port-Channel211.2005
    description PE-CE:ATL-SE1-DC1-N1:Po101.2005
    encapsulation dot1q vlan 2005
    vrf CCMERCH
    ip address 10.77.0.6/31
  !
  interface Port-Channel211.2006
    description PE-CE:ATL-SE1-DC1-N1:Po101.2006
    encapsulation dot1q vlan 2006
    vrf CCHYBRID
    ip address 10.77.0.8/31
  !
  interface Port-Channel212
    description PE-CE:ATL-SE1-DC1-N2:Po101
    no switchport
  !
  interface Port-Channel212.2001
    description PE-CE:ATL-SE1-DC1-N2:Po101.2001
    encapsulation dot1q vlan 2001
    vrf DCX1
    ip address 10.77.0.20/31
  !
  interface Port-Channel212.2002
    description PE-CE:ATL-SE1-DC1-N2:Po101.2002
    encapsulation dot1q vlan 2002
    vrf PEN1
    ip address 10.77.0.22/31
  !
  interface Port-Channel212.2004
    description PE-CE:ATL-SE1-DC1-N2:Po101.2004
    encapsulation dot1q vlan 2004
    vrf CCISSUE
    ip address 10.77.0.24/31
  !
  interface Port-Channel212.2005
    description PE-CE:ATL-SE1-DC1-N2:Po101.2005
    encapsulation dot1q vlan 2005
    vrf CCMERCH
    ip address 10.77.0.26/31
  !
  interface Port-Channel212.2006
    description PE-CE:ATL-SE1-DC1-N2:Po101.2006
    encapsulation dot1q vlan 2006
    vrf CCHYBRID
    ip address 10.77.0.28/31
  !
  interface Ethernet1/1
    description PE-CE:ATL-SI1-DC1-N1:Eth3/49/1
    no shutdown
    no switchport
    channel-group 110 mode active
  !
  interface Ethernet2/1
    description PE-CE:ATL-SI1-DC1-N2:Eth3/49/1
    no shutdown
    no switchport
    channel-group 111 mode active
  !
  interface Ethernet2/3
    shutdown
    no switchport
  !
  interface Ethernet3/1
    description PE-CE:ATL-ST1-DC1-N1:Eth3/49/1
    no shutdown
    no switchport
    channel-group 114 mode active
  !
  interface Ethernet4/1
    description PE-CE:ATL-ST1-DC1-N2:Eth3/49/1
    no shutdown
    no switchport
    channel-group 115 mode active
  !
  interface Ethernet15/1
    no shutdown
    no switchport
  !
  interface Ethernet15/1.2020
    description PE-CE:ATL-UI1-DC1-N1:Eth49/1.2020
    encapsulation dot1q vlan 2020
    vrf USX1
    ip address 10.48.139.0/31
    ip access-group ACL_RO_TRAFFIC_INBOUND in
  !
  interface Ethernet15/1.2820
    description PE-CE:ATL-UI1-DC1-N1:Eth49/1.2820
    encapsulation dot1q vlan 2820
    vrf USUNT1
    ip address 10.111.125.32/31
  !
  interface Ethernet16/1
    no shutdown
    no switchport
  !
  interface Ethernet16/1.2020
    description PE-CE:ATL-UI1-DC1-N2:Eth49/1.2020
    encapsulation dot1q vlan 2020
    vrf USX1
    ip address 10.48.139.2/31
    ip access-group ACL_RO_TRAFFIC_INBOUND in
  !
  interface Ethernet16/1.2820
    description PE-CE:ATL-UI1-DC1-N2:Eth49/1.2820
    encapsulation dot1q vlan 2820
    vrf USUNT1
    ip address 10.111.125.34/31
  !
  interface Ethernet21/1
    description PE-CE:ATL-SE1-DC1-N1:Eth3/49/1
    no shutdown
    no switchport
    channel-group 211 mode active
  !
  interface Ethernet22/1
    description PE-CE:ATL-SE1-DC1-N2:Eth3/49/1
    no shutdown
    no switchport
    channel-group 212 mode active
  !
  interface Ethernet23/1
    description PE-CE:ATL-SOB1-DC1-N1:Eth3/49/1
    no shutdown
    no switchport
    channel-group 116 mode active
  !
  interface Ethernet24/1
    description PE-CE:ATL-SOB1-DC1-N2:Eth3/49/1
    no shutdown
    no switchport
    channel-group 117 mode active
  !
  interface Ethernet25/1
    description P-PE:ATL-TRX1-DC1-P1:Eth25/1
    no shutdown
    no switchport
    ip address 10.199.2.43/31
    mpls ldp interface
    mac security profile MKA_AES_256
    ip ospf network point-to-point
    ip ospf authentication message-digest
    ip ospf area 0.0.0.0
    ip ospf message-digest-key 1 md5 7 gI+W5b1R4lDpehCmYzyW2w==
  !
  interface Ethernet26/1
    description P-PE:ATL-TRX1-DC1-P2:Eth25/1
    no shutdown
    no switchport
    ip address 10.199.2.45/31
    mpls ldp interface
    mac security profile MKA_AES_256
    ip ospf network point-to-point
    ip ospf authentication message-digest
    ip ospf area 0.0.0.0
    ip ospf message-digest-key 1 md5 7 2N0AcrEZMpyItTIpN+dU7Q==
  !
  interface Loopback0
    description MPLS_Overlay_peering
    ip address 10.199.0.28/32
    ip ospf area 0.0.0.0
  !
  interface Management1
    description oob_management
    no shutdown
    vrf MGMT
    ip address 10.9.182.151/28
  !

network_ports:
  - switches:
    - atl-trx1-dc1-pe1
    switch_ports:
    - Ethernet1/2
    - Ethernet3/1
    - Ethernet4/3
    - Ethernet5/1
    - Ethernet6/1
    - Ethernet7/1
    - Ethernet8/1
    - Ethernet9/1
    - Ethernet10/1
    - Ethernet11/1
    - Ethernet12/1
    - Ethernet13/1
    - Ethernet14/1
    - Ethernet17/1
    - Ethernet18/1
    - Ethernet19/1
    - Ethernet20/1
    - Ethernet21/2
    - Ethernet22/3
    - Ethernet23/2
    - Ethernet24/3
    - Ethernet25/2
    - Ethernet26/3
    - Ethernet27/1
    - Ethernet28/1
    - Ethernet29/1
    - Ethernet30/1
    - Ethernet31/2
    - Ethernet33/1
    - Ethernet34/1
    - Ethernet35/1
    - Ethernet36/1
    raw_eos_cli: |-
      no switchport
      shutdown